name: 发布至阿里云Docker镜像服务

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
  - cron: "0 0 * * *"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
        - source: hello-world
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/hello-world
        - source: fauria/vsftpd
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/vsftpd
        - source: atmoz/sftp
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/sftp
        - source: bytemark/webdav
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/webdav
        - source: dockurr/samba
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/samba
        - source: xhofe/alist
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/alist
        - source: itsthenetwork/nfs-server-alpine
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/nfs-server-alpine
        - source: itzg/minecraft-server
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/minecraft-server
        - source: adguard/adguardhome
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/adguardhome
        - source: vaultwarden/server
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/vaultwarden_server
        - source: nginx
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/nginx
        - source: nginx:stable-alpine
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/nginx:stable-alpine
        - source: lanol/filecodebox
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/filecodebox
        - source: binwiederhier/ntfy
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/ntfy
        - source: homeassistant/home-assistant
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/home-assistant
        - source: teamspeak
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/teamspeak

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ vars.USERNAME }}
        password: ${{ secrets.TOKEN }}

    - name: Build, tag, and push image
      run: |
        echo "Processing ${{ matrix.image.source }} -> ${{ matrix.image.target }}"
        docker pull "${{ matrix.image.source }}"
        docker tag "${{ matrix.image.source }}" "${{ matrix.image.target }}"
        docker push "${{ matrix.image.target }}"
        docker rmi -f "${{ matrix.image.source }}" "${{ matrix.image.target }}"
        echo "Done with ${{ matrix.image.source }} -> ${{ matrix.image.target }}"
        echo "-------------------------------------"
