name: Docker Mirror

on:
  workflow_dispatch:
  schedule:
  - cron: "0 16 * * *"

env:
  REGISTRYNAME: registry.cn-hangzhou.aliyuncs.com/blazesnow/
  USERNAME: BlazeSnow23

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        image:
        - source: hello-world:latest
          target: hello-world:latest
        - source: fauria/vsftpd:latest
          target: vsftpd:latest
        - source: atmoz/sftp:latest
          target: sftp:latest
        - source: bytemark/webdav:latest
          target: webdav:latest
        - source: dockurr/samba:latest
          target: samba:latest
        - source: itsthenetwork/nfs-server-alpine:latest
          target: nfs-server-alpine:latest
        - source: itzg/minecraft-server:latest
          target: minecraft-server:latest
        - source: adguard/adguardhome:latest
          target: adguardhome:latest
        - source: vaultwarden/server:latest
          target: vaultwarden_server:latest
        - source: nginx:latest
          target: nginx:latest
        - source: nginx:mainline-alpine
          target: nginx:mainline-alpine
        - source: nginx:stable-alpine
          target: nginx:stable-alpine
        - source: lanol/filecodebox:latest
          target: filecodebox:latest
        - source: binwiederhier/ntfy:latest
          target: ntfy:latest
        - source: homeassistant/home-assistant:latest
          target: home-assistant:latest
        - source: homeassistant/home-assistant:stable
          target: home-assistant:stable
        - source: teamspeak:latest
          target: teamspeak:latest
        - source: deluan/navidrome:latest
          target: navidrome:latest
        - source: portainer/portainer-ce:alpine
          target: portainer-ce:alpine
        - source: portainer/agent:alpine
          target: portainer-agent:alpine
        - source: busybox:latest
          target: busybox:latest
        - source: mysql:8.0.42
          target: mysql:8.0.42
        - source: certbot/certbot:latest
          target: certbot:latest
        - source: caddy:alpine
          target: caddy:alpine

    steps:
    - name: login
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRYNAME }}
        username: ${{ env.USERNAME }}
        password: ${{ secrets.TOKEN }}
        logout: true

    - name: docker pull
      run: docker pull ${{ matrix.image.source }}

    - name: docker tag
      run: docker tag ${{ matrix.image.source }} ${{ env.REGISTRYNAME }}${{ matrix.image.target }}

    - name: docker push
      run: docker push ${{ env.REGISTRYNAME }}${{ matrix.image.target }}

    - name: docker rmi
      run: docker rmi ${{ matrix.image.source }} ${{ env.REGISTRYNAME }}${{ matrix.image.target }}
