name: Docker Mirror

on:
  push:
    branches:
    - main
  workflow_dispatch:
  schedule:
  - cron: "0 16 * * *"

env:
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  NAMESPACE: blazesnow
  USERNAME: BlazeSnow23

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: login
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.USERNAME }}
        password: ${{ secrets.TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: chmod
      run: chmod +x ./dockermirror.sh

    - name: docker pull, tag, push and clean
      env:
        REGISTRY: ${{ env.REGISTRY }}
        NAMESPACE: ${{ env.NAMESPACE }}
      run: ./dockermirror.sh
