name: Docker Mirror

on:
  workflow_dispatch:
  schedule:
  - cron: "0 16 * * *"

env:
  REGISTRYNAME: registry.cn-hangzhou.aliyuncs.com/blazesnow/
  USERNAME: BlazeSnow23

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        image:
        - source: hello-world
          target: hello-world
        - source: fauria/vsftpd
          target: vsftpd
        - source: atmoz/sftp
          target: sftp
        - source: bytemark/webdav
          target: webdav
        - source: dockurr/samba
          target: samba
        - source: itsthenetwork/nfs-server-alpine
          target: nfs-server-alpine
        - source: itzg/minecraft-server
          target: minecraft-server
        - source: adguard/adguardhome
          target: adguardhome
        - source: vaultwarden/server
          target: vaultwarden_server
        - source: nginx
          target: nginx
        - source: nginx:mainline-alpine
          target: nginx:mainline-alpine
        - source: nginx:stable-alpine
          target: nginx:stable-alpine
        - source: lanol/filecodebox
          target: filecodebox
        - source: binwiederhier/ntfy
          target: ntfy
        - source: homeassistant/home-assistant
          target: home-assistant
        - source: teamspeak
          target: teamspeak
        - source: mysql:8.0.42
          target: mysql:8.0.42
        - source: certbot/certbot
          target: certbot

    steps:
    - name: login
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRYNAME }}
        username: ${{ env.USERNAME }}
        password: ${{ secrets.TOKEN }}
        logout: true

    - name: docker pull
      run: docker pull ${{ matrix.image.source }}

    - name: docker tag
      run: docker tag ${{ matrix.image.source }} ${{ env.REGISTRYNAME }}${{ matrix.image.target }}

    - name: docker push
      run: docker push ${{ env.REGISTRYNAME }}${{ matrix.image.target }}

    - name: docker rmi
      run: docker rmi ${{ matrix.image.source }} ${{ env.REGISTRYNAME }}${{ matrix.image.target }}
