name: 发布至阿里云Docker镜像服务

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
  - cron: "0 0 * * *"

jobs:
  sync-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
        - source: hello-world
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/hello-world
        - source: fauria/vsftpd
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/vsftpd
        - source: atmoz/sftp
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/sftp
        - source: bytemark/webdav
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/webdav
        - source: dockurr/samba
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/samba
        - source: xhofe/alist
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/alist
        - source: itsthenetwork/nfs-server-alpine
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/nfs-server-alpine
        - source: itzg/minecraft-server
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/minecraft-server
        - source: adguard/adguardhome
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/adguardhome
        - source: vaultwarden/server
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/vaultwarden_server
        - source: nginx
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/nginx
        - source: nginx:mainline-alpine
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/nginx:mainline-alpine
        - source: nginx:stable-alpine
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/nginx:stable-alpine
        - source: lanol/filecodebox
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/filecodebox
        - source: binwiederhier/ntfy
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/ntfy
        - source: homeassistant/home-assistant
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/home-assistant
        - source: teamspeak
          target: registry.cn-hangzhou.aliyuncs.com/blazesnow/teamspeak

    steps:
    - name: Log in to Alibaba Cloud Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ vars.USERNAME }}
        password: ${{ secrets.TOKEN }}

    - name: Pull, Tag, and Push Image
      run: |
        set -e
        SOURCE_IMAGE="${{ matrix.image.source }}"
        TARGET_IMAGE="${{ matrix.image.target }}"

        echo "-------------------------------------"
        echo "Syncing image: ${SOURCE_IMAGE} -> ${TARGET_IMAGE}"

        echo "Pulling source image: ${SOURCE_IMAGE}"
        docker pull "${SOURCE_IMAGE}"

        echo "Tagging image: ${SOURCE_IMAGE} as ${TARGET_IMAGE}"
        docker tag "${SOURCE_IMAGE}" "${TARGET_IMAGE}"

        echo "Pushing target image: ${TARGET_IMAGE}"
        docker push "${TARGET_IMAGE}"

        echo "Cleaning up local images: ${SOURCE_IMAGE}, ${TARGET_IMAGE}"
        docker rmi "${SOURCE_IMAGE}" "${TARGET_IMAGE}" || echo "Local cleanup failed for ${SOURCE_IMAGE}, continuing..."

        echo "Successfully synced: ${SOURCE_IMAGE} -> ${TARGET_IMAGE}"
        echo "-------------------------------------"
      env:
        SOURCE_IMAGE: ${{ matrix.image.source }}
        TARGET_IMAGE: ${{ matrix.image.target }}
